/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.wavemaker.sampleapps.wavekart.demojavaservice.controller;

import com.wavemaker.sampleapps.wavekart.demojavaservice.DemoJavaService;
import com.wavemaker.sampleapps.wavekart.demojavaservice.DemoJavaService.MyPojo;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/demoJava", produces = { "application/json", "application/xml" })
public class DemoJavaController {

    @Autowired
    private DemoJavaService demoJavaService;

    @RequestMapping(value = "/inputMyPojo", produces = "application/json", method = RequestMethod.POST)
    public String inputMyPojo(@RequestBody MyPojo mypojo) {
        return demoJavaService.inputMyPojo(mypojo);
    }

    @RequestMapping(value = "/sampleJavaOperation", produces = "application/json", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name) {
        return demoJavaService.sampleJavaOperation(name);
    }

    @RequestMapping(value = "/sayHello", produces = "application/json", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String sayHello(@RequestParam(value = "name", required = false) String name) {
        return demoJavaService.sayHello(name);
    }
}
