/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/


package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class EshoppingQueryExecutorServiceImpl implements EshoppingQueryExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(EshoppingQueryExecutorServiceImpl.class);

	@Autowired
	@Qualifier("eshoppingWMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public int executeOrdered( java.lang.String data, java.lang.String data2)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("data", data);
        params.put("data2", data2);
        return queryExecutor.executeNamedQueryForUpdate("Ordered", params);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> execute_Total_Price(Pageable pageable, java.lang.String data)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("data", data);
        return queryExecutor.executeNamedQuery("_Total_Price", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public int executeCancelled( java.lang.String data, java.lang.Integer data1)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("data", data);
        params.put("data1", data1);
        return queryExecutor.executeNamedQueryForUpdate("cancelled", params);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> execute_Total_InCart(Pageable pageable)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        return queryExecutor.executeNamedQuery("_Total_InCart", params, pageable);
	}
	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> execute_OrderedLists(Pageable pageable, java.lang.Integer LoggedinUserID)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("LoggedinUserID", LoggedinUserID);
        return queryExecutor.executeNamedQuery("_OrderedLists", params, pageable);
	}

	@Transactional(value = "eshoppingTransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "eshoppingTransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

