/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.wavemaker.sampleapps.wavekart.eshopping.*;
import com.wavemaker.sampleapps.wavekart.eshopping.Itemorder;

/**
 * Service object for domain model class Itemorder.
 * @see Itemorder
 */

public interface ItemorderService {
   /**
	 * Creates a new itemorder.
	 * 
	 * @param created
	 *            The information of the created itemorder.
	 * @return The created itemorder.
	 */
	public Itemorder create(Itemorder created);

	/**
	 * Deletes a itemorder.
	 * 
	 * @param itemorderId
	 *            The id of the deleted itemorder.
	 * @return The deleted itemorder.
	 * @throws EntityNotFoundException
	 *             if no itemorder is found with the given id.
	 */
	public Itemorder delete(Integer itemorderId) throws EntityNotFoundException;

	/**
	 * Finds all itemorders.
	 * 
	 * @return A list of itemorders.
	 */
	public Page<Itemorder> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Itemorder> findAll(Pageable pageable);
	
	/**
	 * Finds itemorder by id.
	 * 
	 * @param id
	 *            The id of the wanted itemorder.
	 * @return The found itemorder. If no itemorder is found, this method returns
	 *         null.
	 */
	public Itemorder findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a itemorder.
	 * 
	 * @param updated
	 *            The information of the updated itemorder.
	 * @return The updated itemorder.
	 * @throws EntityNotFoundException
	 *             if no itemorder is found with given id.
	 */
	public Itemorder update(Itemorder updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the itemorders in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the itemorder.
	 */

	public long countAll();


    public Page<Itemorder> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

