/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.wavemaker.sampleapps.wavekart.eshopping.*;
import com.wavemaker.sampleapps.wavekart.eshopping.Orderdetail;


/**
 * ServiceImpl object for domain model class Orderdetail.
 * @see Orderdetail
 */
@Service("eshopping.OrderdetailService")
public class OrderdetailServiceImpl implements OrderdetailService {


    private static final Logger LOGGER = LoggerFactory.getLogger(OrderdetailServiceImpl.class);

    @Autowired
    @Qualifier("eshopping.OrderdetailDao")
    private WMGenericDao<Orderdetail, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Orderdetail, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "eshoppingTransactionManager")
     public Page<Orderdetail> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "eshoppingTransactionManager")
    @Override
    public Orderdetail create(Orderdetail orderdetail) {
        LOGGER.debug("Creating a new orderdetail with information: {}" , orderdetail);
        return this.wmGenericDao.create(orderdetail);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "eshoppingTransactionManager")
    @Override
    public Orderdetail delete(Integer orderdetailId) throws EntityNotFoundException {
        LOGGER.debug("Deleting orderdetail with id: {}" , orderdetailId);
        Orderdetail deleted = this.wmGenericDao.findById(orderdetailId);
        if (deleted == null) {
            LOGGER.debug("No orderdetail found with id: {}" , orderdetailId);
            throw new EntityNotFoundException(String.valueOf(orderdetailId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public Page<Orderdetail> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all orderdetails");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public Page<Orderdetail> findAll(Pageable pageable) {
        LOGGER.debug("Finding all orderdetails");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public Orderdetail findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding orderdetail by id: {}" , id);
        Orderdetail orderdetail=this.wmGenericDao.findById(id);
        if(orderdetail==null){
            LOGGER.debug("No orderdetail found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return orderdetail;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "eshoppingTransactionManager")
    @Override
    public Orderdetail update(Orderdetail updated) throws EntityNotFoundException {
        LOGGER.debug("Updating orderdetail with information: {}" , updated);
        this.wmGenericDao.update(updated);

        Integer id = (Integer)updated.getId();

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


