/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.wavemaker.sampleapps.wavekart.eshopping.*;
import com.wavemaker.sampleapps.wavekart.eshopping.Productorder;

/**
 * Service object for domain model class Productorder.
 * @see Productorder
 */

public interface ProductorderService {
   /**
	 * Creates a new productorder.
	 * 
	 * @param created
	 *            The information of the created productorder.
	 * @return The created productorder.
	 */
	public Productorder create(Productorder created);

	/**
	 * Deletes a productorder.
	 * 
	 * @param productorderId
	 *            The id of the deleted productorder.
	 * @return The deleted productorder.
	 * @throws EntityNotFoundException
	 *             if no productorder is found with the given id.
	 */
	public Productorder delete(Integer productorderId) throws EntityNotFoundException;

	/**
	 * Finds all productorders.
	 * 
	 * @return A list of productorders.
	 */
	public Page<Productorder> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Productorder> findAll(Pageable pageable);
	
	/**
	 * Finds productorder by id.
	 * 
	 * @param id
	 *            The id of the wanted productorder.
	 * @return The found productorder. If no productorder is found, this method returns
	 *         null.
	 */
	public Productorder findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a productorder.
	 * 
	 * @param updated
	 *            The information of the updated productorder.
	 * @return The updated productorder.
	 * @throws EntityNotFoundException
	 *             if no productorder is found with given id.
	 */
	public Productorder update(Productorder updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the productorders in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the productorder.
	 */

	public long countAll();


    public Page<Productorder> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

