/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/





import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.wavemaker.sampleapps.wavekart.eshopping.*;
import com.wavemaker.sampleapps.wavekart.eshopping.Productorder;


/**
 * ServiceImpl object for domain model class Productorder.
 * @see Productorder
 */
@Service("eshopping.ProductorderService")
public class ProductorderServiceImpl implements ProductorderService {


    private static final Logger LOGGER = LoggerFactory.getLogger(ProductorderServiceImpl.class);

    @Autowired
    @Qualifier("eshopping.ProductorderDao")
    private WMGenericDao<Productorder, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Productorder, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "eshoppingTransactionManager")
     public Page<Productorder> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "eshoppingTransactionManager")
    @Override
    public Productorder create(Productorder productorder) {
        LOGGER.debug("Creating a new productorder with information: {}" , productorder);
        return this.wmGenericDao.create(productorder);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "eshoppingTransactionManager")
    @Override
    public Productorder delete(Integer productorderId) throws EntityNotFoundException {
        LOGGER.debug("Deleting productorder with id: {}" , productorderId);
        Productorder deleted = this.wmGenericDao.findById(productorderId);
        if (deleted == null) {
            LOGGER.debug("No productorder found with id: {}" , productorderId);
            throw new EntityNotFoundException(String.valueOf(productorderId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public Page<Productorder> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all productorders");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public Page<Productorder> findAll(Pageable pageable) {
        LOGGER.debug("Finding all productorders");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public Productorder findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding productorder by id: {}" , id);
        Productorder productorder=this.wmGenericDao.findById(id);
        if(productorder==null){
            LOGGER.debug("No productorder found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return productorder;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "eshoppingTransactionManager")
    @Override
    public Productorder update(Productorder updated) throws EntityNotFoundException {
        LOGGER.debug("Updating productorder with information: {}" , updated);
        this.wmGenericDao.update(updated);

        Integer id = (Integer)updated.getId();

        return this.wmGenericDao.findById(id);
    }

    @Transactional(readOnly = true, value = "eshoppingTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


